name: CI/CD Pipeline with Security Check (No Source Code)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build Step (No Source Code)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Placeholder
        run: |
          echo "No source code to build."
          echo "Build step complete."

  security-check:
    name: Security Vulnerability Scan with CodeQL
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python # Add any language, even if no code is present

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true # Prevents the workflow from failing due to no source code
