name: CI/CD Pipeline with Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          echo "Building project..."
          # Add your build commands here, for example:
          # make build
          echo "Build complete."

  security-check:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp # Replace with your project's language (e.g., python, java, csharp)

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
